// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBulAQp0y1jBD4nqMVwitTXJmktOE2An1Q',
    appId: '1:883846931977:web:8130626f2da34895427ad8',
    messagingSenderId: '883846931977',
    projectId: 'law-counsel',
    authDomain: 'law-counsel.firebaseapp.com',
    storageBucket: 'law-counsel.firebasestorage.app',
    measurementId: 'G-YKE6TN1672',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVAV1CcJEcEfbCiF4zsgAQb5zg0xGOwhc',
    appId: '1:883846931977:android:0691a37a9f8c1fb4427ad8',
    messagingSenderId: '883846931977',
    projectId: 'law-counsel',
    storageBucket: 'law-counsel.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBulAQp0y1jBD4nqMVwitTXJmktOE2An1Q',
    appId: '1:883846931977:web:5b54b8aae2731042427ad8',
    messagingSenderId: '883846931977',
    projectId: 'law-counsel',
    authDomain: 'law-counsel.firebaseapp.com',
    storageBucket: 'law-counsel.firebasestorage.app',
    measurementId: 'G-7K17NVYGG5',
  );
}
